version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: movie
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_pw
    volumes:
      - db-volume:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
volumes:
  db-volume:
